services:
  # १. बॅकएंड सर्व्हिस (Web Service)
  - type: web
    name: rescuify-backend
    env: node
    repo: https://github.com/dev-anii/Rescuify-AI  # तुझा गिटहब पाथ
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GROQ_API_KEY
        value: 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 # तुझी की इथे सुरक्षित राहील

  # २. फ्रंटएंड सर्व्हिस (Static Site)
  - type: web
    name: rescuify-frontend
    env: static
    repo: https://github.com/dev-anii/Rescuify-AI
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://rescuify-backend.onrender.com/api/* # बॅकएंड कडे रीबूट होईल
      - type: rewrite
        source: /*
        destination: /index.html